const sellers = [
  { name: "Lucia Fernandez", avatar: "/api/avatar/Lucia-Fernandez.svg", rating: 4.8 },
  { name: "Martin Silva", avatar: "/api/avatar/Martin-Silva.svg", rating: 4.6 },
  { name: "Camila Rocha", avatar: "/api/avatar/Camila-Rocha.svg", rating: 5.0 },
  { name: "Diego Pereira", avatar: "/api/avatar/Diego-Pereira.svg", rating: 4.7 }
];

const image = (seed) => `/api/demo-photo/${seed}.svg`;

const products = [
  {
    id: "item-1",
    title: "Honda Civic EX 2018 impecable",
    price: 18800,
    category: "Vehiculos",
    condition: "Usado",
    location: "Pocitos, Montevideo",
    distance: 4,
    description: "Sedan automatico, service oficial, cubiertas nuevas y muy buen consumo. Acepto revision mecanica.",
    images: [image("civic-1"), image("civic-2"), image("civic-3")],
    seller: sellers[1],
    postedAt: "Hace 2 horas",
    status: "active"
  },
  {
    id: "item-2",
    title: "Apartamento 2 dormitorios con balcon",
    price: 129000,
    category: "Inmuebles",
    condition: "Usado",
    location: "Cordon, Montevideo",
    distance: 6,
    description: "Luminoso, al frente, cocina definida y bajos gastos comunes. Ideal vivienda o renta.",
    images: [image("apartment-1"), image("apartment-2"), image("apartment-3")],
    seller: sellers[0],
    postedAt: "Ayer",
    status: "active"
  },
  {
    id: "item-3",
    title: "iPhone 15 Pro 256 GB",
    price: 980,
    category: "Electronica",
    condition: "Usado",
    location: "Malvin, Montevideo",
    distance: 8,
    description: "Bateria 94%, libre de fabrica, con caja, cable y funda original.",
    images: [image("iphone-15-pro"), image("phone-box")],
    seller: sellers[2],
    postedAt: "Hace 30 min",
    status: "active"
  },
  {
    id: "item-4",
    title: "Sofa esquinero gris 3 cuerpos",
    price: 420,
    category: "Hogar",
    condition: "Usado",
    location: "Carrasco, Montevideo",
    distance: 12,
    description: "Tela antimanchas, estructura firme, se retira por domicilio.",
    images: [image("gray-sofa"), image("living-room")],
    seller: sellers[3],
    postedAt: "Hace 5 horas",
    status: "active"
  },
  {
    id: "item-5",
    title: "Bicicleta Trek Marlin 6",
    price: 650,
    category: "Deportes",
    condition: "Usado",
    location: "Parque Rodo, Montevideo",
    distance: 3,
    description: "Rodado 29, talle M, frenos hidraulicos y transmision Shimano.",
    images: [image("trek-bike"), image("mountain-bike")],
    seller: sellers[0],
    postedAt: "Hoy",
    status: "active"
  },
  {
    id: "item-6",
    title: "Campera de cuero negra",
    price: 120,
    category: "Ropa",
    condition: "Usado",
    location: "Centro, Montevideo",
    distance: 2,
    description: "Talle M, cuero genuino, poco uso. Corte clasico.",
    images: [image("black-jacket"), image("leather-jacket")],
    seller: sellers[2],
    postedAt: "Hace 1 dia",
    status: "active"
  },
  {
    id: "item-7",
    title: "Nintendo Switch OLED con juegos",
    price: 390,
    category: "Entretenimiento",
    condition: "Usado",
    location: "Buceo, Montevideo",
    distance: 9,
    description: "Incluye dock, joy-con, Mario Kart y Zelda. Funcionando perfecto.",
    images: [image("switch-oled"), image("gaming-console")],
    seller: sellers[1],
    postedAt: "Hace 3 dias",
    status: "active"
  },
  {
    id: "item-8",
    title: "Set LEGO Technic sin abrir",
    price: 210,
    category: "Juguetes",
    condition: "Nuevo",
    location: "La Blanqueada, Montevideo",
    distance: 5,
    description: "Caja sellada, ideal regalo. Entrego en shopping Tres Cruces.",
    images: [image("lego-technic"), image("toy-box")],
    seller: sellers[3],
    postedAt: "Hace 4 horas",
    status: "active"
  },
  {
    id: "item-9",
    title: "MacBook Air M2 13 pulgadas",
    price: 1150,
    category: "Electronica",
    condition: "Usado",
    location: "Punta Carretas, Montevideo",
    distance: 4,
    description: "8 GB RAM, 512 GB SSD, bateria excelente, sin golpes ni detalles.",
    images: [image("macbook-air-m2"), image("laptop-desk")],
    seller: sellers[0],
    postedAt: "Hace 6 horas",
    status: "active"
  },
  {
    id: "item-10",
    title: "Mesa comedor madera maciza",
    price: 540,
    category: "Hogar",
    condition: "Usado",
    location: "Prado, Montevideo",
    distance: 10,
    description: "Mesa para 6 personas, excelente estado, madera lustrada.",
    images: [image("wood-table"), image("dining-room")],
    seller: sellers[1],
    postedAt: "Hace 2 dias",
    status: "active"
  },
  {
    id: "item-11",
    title: "Kit mancuernas ajustables 20 kg",
    price: 160,
    category: "Deportes",
    condition: "Nuevo",
    location: "Aguada, Montevideo",
    distance: 6,
    description: "Par de mancuernas con discos intercambiables y estuche.",
    images: [image("dumbbells"), image("home-gym")],
    seller: sellers[2],
    postedAt: "Hoy",
    status: "active"
  },
  {
    id: "item-12",
    title: "Vestido largo azul noche",
    price: 85,
    category: "Ropa",
    condition: "Usado",
    location: "Tres Cruces, Montevideo",
    distance: 5,
    description: "Talle S, usado una vez, tela con muy buena caida.",
    images: [image("blue-dress"), image("fashion-dress")],
    seller: sellers[3],
    postedAt: "Hace 8 horas",
    status: "active"
  },
  {
    id: "item-13",
    title: "PlayStation 5 con dos controles",
    price: 690,
    category: "Entretenimiento",
    condition: "Usado",
    location: "Union, Montevideo",
    distance: 7,
    description: "Edicion disco, poco uso, incluye FIFA y soporte de carga.",
    images: [image("playstation-5"), image("dual-controller")],
    seller: sellers[0],
    postedAt: "Hace 1 hora",
    status: "active"
  },
  {
    id: "item-14",
    title: "Silla ergonomica oficina",
    price: 230,
    category: "Hogar",
    condition: "Nuevo",
    location: "Ciudad Vieja, Montevideo",
    distance: 3,
    description: "Apoyo lumbar, altura regulable, respaldo mesh y garantia.",
    images: [image("office-chair"), image("desk-chair")],
    seller: sellers[1],
    postedAt: "Hace 20 min",
    status: "active"
  },
  {
    id: "item-15",
    title: "Toyota Hilux SRV 2020",
    price: 34800,
    category: "Vehiculos",
    condition: "Usado",
    location: "Las Piedras, Canelones",
    distance: 24,
    description: "4x4 diesel, unico dueno, mantenimiento al dia y documentacion pronta.",
    images: [image("toyota-hilux"), image("pickup-truck")],
    seller: sellers[2],
    postedAt: "Hace 4 dias",
    status: "active"
  }
];

const conversations = [];

module.exports = { products, conversations };
